# Site settings

title: "Eurovision Scoreboard"

description: "A digital scoreboard for your Eurovision house party"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elroid.github.io"
author: "Elliot Long"

# Images and assets
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"

hero-images-path: "/assets/images/hero"
social-images-path: "/assets/images/social"
post-images-path: "/assets/images/posts"

logo-png: "/assets/images/site/logo.png"
logo-svg: "/assets/images/site/logo.svg"
four-oh-four-svg: "/assets/images/site/four-oh-four.svg"

social-media-image: "/assets/images/site/social-media.png"

touch: "/assets/images/site/touch.png"
pinned: "/assets/images/site/pinned.svg"
pinned-colour: "#ff2a68"
logo-favicon-small: "/assets/images/site/favicon-16x16.png"
logo-favicon-medium: "/assets/images/site/favicon-32x32.png"
logo-favicon-large: "/assets/images/site/favicon-96x96.png"


# Social settings
twitter-username: "elroid" # Twitter handle i.e. joebloggs
github-username:  "elroid"
#google-site-verification: "DaqGCZ6cZIqm7q_nVSnOzjJmFFjbRfW2X7FDzpQDQZk" # GSV code; proves domain ownership

#Analytics
disable-analytics: false # Switch to "false" to start GA logging
google-analytics: "UA-27553664-1" # GA ID code

# Plugins and build settings

permalink: pretty
markdown: kramdown
future: false
sass:
    sass_dir: _sass
    #sourcemap: true
    

plugins:
- jekyll-redirect-from